// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7uNkZ6ET4AhCq_rzP98sDPwkmmQqLivE',
    appId: '1:259361655226:web:9cfd5d638739c16060f583',
    messagingSenderId: '259361655226',
    projectId: 'kaapi-club',
    authDomain: 'kaapi-club.firebaseapp.com',
    storageBucket: 'kaapi-club.appspot.com',
    measurementId: 'G-ENH8GP422M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjhtQmuFp2X7ugxOKH-FLTzOncXq6KHQ',
    appId: '1:259361655226:android:77450100d0b4781c60f583',
    messagingSenderId: '259361655226',
    projectId: 'kaapi-club',
    storageBucket: 'kaapi-club.appspot.com',
  );
}
